stages:
  - build

build:
  stage : build
  script: |
    cd ~/runners/$CI_RUNNER_ID/chipyard
    git pull
    if [ -d generators/boom.tmp ]; then
        mv -f generators/boom generators/boom.working
        mv -f generators/boom.tmp generators/boom
        ./scripts/init-submodules-no-riscv-tools.sh
        mv -f generators/boom generators/boom.tmp
        mv -f generators/boom.working generators/boom
    else
        ./scripts/init-submodules-no-riscv-tools.sh
        mv -f generators/boom generators/boom.tmp
    fi
    rsync -az $CI_PROJECT_DIR/* generators/boom
    module load chipyard
    make -C sims/vcs CONFIG=StcBoomConfig -j
    make -C sims/vcs CONFIG=StcBoomConfig -j run-asm-tests
    make -C sims/vcs CONFIG=StcBoomConfig -j run-bmark-tests
    cd toolchains/llvm/riscv-testsuite
    ./scripts/run-basic.sh --vcs=../../../sims/vcs/simv-chipyard-StcBoomConfig --cases=sanity.list
    cd ../../..
  timeout: 5h
  artifacts:
    paths:
      - chipyard/sims/vcs/simv-chipyard-StcBoomConfig
    name: simv
  tags:
    - lsf

